//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_Migration
{
    using System;
    using System.Collections.Generic;
    
    public partial class per
    {
        public string rt { get; set; }
        public string ex { get; set; }
        public Nullable<double> ytd { get; set; }
        public Nullable<double> five_day { get; set; }
        public Nullable<double> one_month { get; set; }
        public Nullable<double> three_month { get; set; }
        public Nullable<double> one_year { get; set; }
    }
}
