//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ar
    {
        public string rt { get; set; }
        public string ex { get; set; }
        public Nullable<double> ht { get; set; }
        public Nullable<double> lt { get; set; }
        public Nullable<double> met { get; set; }
        public Nullable<double> mdt { get; set; }
    }
}
