//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pr
    {
        public string rt { get; set; }
        public string ex { get; set; }
        public string ex_short { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<double> daily_change { get; set; }
        public Nullable<double> per_dayly_change { get; set; }
        public Nullable<long> vol { get; set; }
        public Nullable<double> week_52_h { get; set; }
        public Nullable<double> week_52_l { get; set; }
    }
}
