//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_s
    {
        public long pKey { get; set; }
        public string Co_ID { get; set; }
        public string Exchange { get; set; }
        public string Name { get; set; }
        public string root__ticker { get; set; }
        public string QMV { get; set; }
        public string OS_Shares { get; set; }
        public string tech_sub_sector { get; set; }
        public string cps { get; set; }
        public string re { get; set; }
        public string Sector { get; set; }
        public string Sub_Sector { get; set; }
        public string type_of_listing { get; set; }
        public string date_of_listing { get; set; }
        public string hq_location { get; set; }
        public string hq_region { get; set; }
        public string interlisted_code_1 { get; set; }
        public string interlisted_code_2 { get; set; }
        public string tsx_ven_grad { get; set; }
        public string former_cpc { get; set; }
        public string Index { get; set; }
        public string technology_sub_sector { get; set; }
        public string usa_city { get; set; }
        public string USA_State { get; set; }
        public string asia_region { get; set; }
        public string place_inCopporated { get; set; }
        public string fundfamily { get; set; }
        public string sp_grouping { get; set; }
        public string SP_Sub { get; set; }
        public string income_trust_conversion { get; set; }
        public string volume_ytd { get; set; }
        public string value__ytd { get; set; }
        public string num_traded_share_ytd { get; set; }
        public string num_of_month_trading_data { get; set; }
        public string AFRICA { get; set; }
        public string AUS_NZ_PNG { get; set; }
        public string CANADA { get; set; }
        public string CHINA__ASIA { get; set; }
        public string LATIN_AMERICA { get; set; }
        public string OTHER { get; set; }
        public string UK_EUROPE { get; set; }
        public string USA { get; set; }
        public string Oil_Gas { get; set; }
        public string Gold { get; set; }
        public string Silver { get; set; }
        public string Copper { get; set; }
        public string Nickel { get; set; }
        public string Diamond { get; set; }
        public string Molybdenum { get; set; }
        public string Platinum_PGM { get; set; }
        public string Iron { get; set; }
        public string Lead { get; set; }
        public string Zinc { get; set; }
        public string Rare_Earths { get; set; }
        public string Potash { get; set; }
        public string Lithium { get; set; }
        public string Uranium { get; set; }
        public string Coal { get; set; }
        public string Tungsten { get; set; }
        public string base__precious_metals { get; set; }
        public string mineral_properties { get; set; }
        public string other_properties { get; set; }
    }
}
